Refactor workflow
canonical/robotics-actions-workflows pull request #4
Opened 2024-10-07 09:29 UTC by artivis

Refactor the overall workflow to split the main build/test/pull jobs.
This also unify the regular & lxc based testing job in a single file. 
Plus it supports the case where multiple snaps must be tested together (build & pub are parallelised).

2024-10-15 08:47 UTC, MirkoFerrati commented on .github/workflows/monitor-upstream.yaml
> +          curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o semver2.sh
"curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o semver2.sh " @artivis this is a supply-chain risk. 
if the repo is taken over they could run scripts in our CI, which may also imply in our self-hosted runners.  Could you pinpoint a specific tag so we don't get new commits in the script we download?

2024-10-15 08:56 UTC, artivis commented on .github/workflows/monitor-upstream.yaml
> +          curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o semver2.sh
I removed this file as well as the other two that don't belong to this pr.

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on .github/workflows/build.yaml
> +        #  echo "artifact-name=$(basename -s .snap ${{ steps.build-snap.outputs.snap }})-$(echo ${{ inputs.git-ref }} | sed "s|\/|\-|g")" >> "$GITHUB_OUTPUT"
To remove.

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on .github/workflows/publish.yaml
> +            echo "Snapstore login is empty !"
```suggestion
            echo "Snapstore login is empty!"
```

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on .github/workflows/publish.yaml
> +
This is already present in the prepare publish.

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on .github/workflows/snap-lxc.yaml
> -name: build-install-test-snap-lxc
Deleting this file will break current workflows. Should we make a workflow with this name calling the main one?

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on .github/workflows/snap.yaml
> +        description: The LXC image to run this action in.
```suggestion
        description: The LXD image to run this action in.
```

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on .github/workflows/test.yaml
> +        description: The LXC image to run this action in.
```suggestion
        description: The LXD image to run this action in.
```

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on .github/workflows/test.yaml
> +          # merge-multiple: true
To remove?

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on README.md
> +As such, it exposes all configurations options of each sub-workflow as detailed in the next section.
```suggestion
As such, it exposes all configuration options of each sub-workflow as detailed in the next section.
```

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on README.md
> +| `lxd-image` | ' ' | The LXC image to run this action in. | false |
```suggestion
| `lxd-image` | ' ' | The LXD image to run this action in. | false |
```

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on README.md
> +It does so using the [canonical/action-build](https://github.com/canonical/action-build) and the snap project it find at the repository root.
```suggestion
It does so using the [canonical/action-build](https://github.com/canonical/action-build) and the snap project it finds at the repository root.
```

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on README.md
> +However the caller may provide an additional custom test as a bash script through the `snap-test-script` option.
```suggestion
However, the caller may provide an additional custom test as a bash script through the `snap-test-script` option.
```

2024-10-15 10:17 UTC, Guillaumebeuzeboc commented on string-to-json/action.yaml
> +#   color: orange
to remove?

2024-10-15 12:42 UTC, artivis commented on .github/workflows/build.yaml
> +        #  echo "artifact-name=$(basename -s .snap ${{ steps.build-snap.outputs.snap }})-$(echo ${{ inputs.git-ref }} | sed "s|\/|\-|g")" >> "$GITHUB_OUTPUT"
Done.

2024-10-15 12:43 UTC, artivis commented on string-to-json/action.yaml
> +#   color: orange
I haven't check what they correspond to yet. I'd leave it as a reminder.

2024-10-15 13:27 UTC, giusebar requested changes

2024-10-15 13:27 UTC, giusebar commented on .github/workflows/snap.yaml
> +        description: The LXD image to run this action in.
this is only to run test in, maybe we should make it clearer here.

2024-10-15 13:27 UTC, giusebar commented on .github/workflows/build.yaml
> +        uses: canonical/robotics-actions-workflows/string-to-json@fix/refactor-matrix
change branch before merging

2024-10-15 13:27 UTC, giusebar commented on .github/workflows/build.yaml
> +        uses: canonical/robotics-actions-workflows/string-to-json@fix/refactor-matrix
change branch before merging

2024-10-15 13:27 UTC, giusebar commented on .github/workflows/test.yaml
> +        uses: canonical/robotics-actions-workflows/string-to-json@fix/refactor-matrix
change branch before merging

2024-10-15 13:27 UTC, giusebar commented on .github/workflows/snap.yaml
> +            echo "defined=false" >> $GITHUB_OUTPUT;
should we fail and exit here?

2024-10-15 13:27 UTC, giusebar commented on .github/workflows/snap-lxc.yaml
> -name: build-install-test-snap-lxc
it should be only these two running on core18: 
- https://github.com/snapcraft-docs/ros-talker-listener/blob/master/.github/workflows/snap.yaml
- https://github.com/snapcraft-docs/ros2-talker-listener/blob/master/.github/workflows/snap.yaml#L16

2024-10-15 13:29 UTC, giusebar commented on .github/workflows/publish.yaml
> +          echo "Files: ${files}"
should this be removed or wnat to leave it there for debugging?

2024-10-15 13:32 UTC, Guillaumebeuzeboc commented on .github/workflows/snap-lxc.yaml
> -name: build-install-test-snap-lxc
Ok then it makes sens to break and fix

2024-10-15 13:33 UTC, giusebar commented on README.md
> +as it names suggests,
```suggestion
as its names suggests,
```

2024-10-15 13:34 UTC, giusebar commented on README.md
> +out of which is uses all the `*.snap` file it finds.
```suggestion
out of which it uses all the `*.snap` file it finds.
```

2024-10-15 13:35 UTC, giusebar commented on README.md
> +The [publish](.github/workflows/publish.yaml) workflow publishes the snap(s(s) built during the run and after they've been tested.
```suggestion
The [publish](.github/workflows/publish.yaml) workflow publishes the snap(s) built during the run and after they've been tested.
```

2024-10-15 13:52 UTC, artivis commented on .github/workflows/publish.yaml
> +          echo "Files: ${files}"
Yup debugging :+1:

2024-10-15 13:52 UTC, artivis commented on README.md
> +as it names suggests,
```suggestion
as its name suggests,
```

2024-10-15 13:59 UTC, artivis commented on .github/workflows/snap.yaml
> +            echo "defined=false" >> $GITHUB_OUTPUT;
It may be undefined on purpose (e.g. no publishing)

2024-10-15 14:00 UTC, artivis commented on .github/workflows/snap.yaml
> +        description: The LXD image to run this action in.
Done.

2024-10-15 14:14 UTC, Guillaumebeuzeboc approved these changes

2024-10-15 14:25 UTC, artivis commented on .github/workflows/build.yaml
> +        uses: canonical/robotics-actions-workflows/string-to-json@fix/refactor-matrix
Will change at the very last minute :+1:

2024-10-15 14:26 UTC, giusebar approved these changes

2024-10-15 15:57 UTC, MirkoFerrati commented on .github/workflows/snap.yaml
> +        uses: geekyeggo/delete-artifact@v5
@Guillaumebeuzeboc how were the rules for self-hosted runners? can we use external github actions? reusable-workflows were forbidden but actions were allowed, right?

2024-10-16 09:29 UTC, Guillaumebeuzeboc commented on .github/workflows/snap.yaml
> +        uses: geekyeggo/delete-artifact@v5
yes.

2024-10-16 09:30 UTC, Guillaumebeuzeboc commented on .github/workflows/snap.yaml
> +        uses: geekyeggo/delete-artifact@v5
I believe GH actions benefit from some security checks that reusable-workflows don't.

2024-10-16 14:01 UTC, MirkoFerrati approved these changes
lgtm!

2024-10-17 14:03 UTC, merged